# Site
title:              Parth P Panchal
bio:                'Passionate software engineer, building machine learning platform at Adobe'
description:        "Passionate software engineer, building machine learning platform at Adobe"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/profilepic.jpg'
#background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://parthpanch.al
navigation:         false

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   pqrth

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:       UA-109590877-1
  verify:          tHE57vQ-1XFiGFACZ6SVF1cp6idvK7bJFbPPEtkfocY
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            pqrth
#facebook:           username
github-url:         pqrth
stackoverflow:     3381334/prth
linkedin:          parthpanchl
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
keybase:           parth
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
